export const s = {
  page: {
    fontFamily: "'Courier New', monospace",
    maxWidth: 580,
    margin: "48px auto",
    padding: "0 24px",
    color: "#111",
  },
  heading: { fontSize: 18, fontWeight: "bold", marginBottom: 2 },
  sub: { fontSize: 12, color: "#666", marginBottom: 32 },
  label: { fontSize: 12, color: "#555", display: "block", marginBottom: 6 },
  row: { display: "flex", gap: 8, marginBottom: 20 },
  input: {
    width: "100%",
    boxSizing: "border-box",
    fontFamily: "'Courier New', monospace",
    fontSize: 13,
    padding: "7px 10px",
    border: "1px solid #ccc",
    borderRadius: 0,
    outline: "none",
    resize: "none",
  },
  runBtn: {
    padding: "6px 18px",
    fontSize: 12,
    background: "#111",
    color: "#fff",
    border: "none",
    cursor: "pointer",
    borderRadius: 0,
    marginTop: 10,
  },
  divider: { borderTop: "1px solid #e0e0e0", margin: "24px 0" },
  barLabel: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: 12,
    marginBottom: 3,
  },
  barTrack: { height: 8, background: "#ebebeb", marginBottom: 14 },
  insightBox: {
    fontSize: 12,
    lineHeight: 1.7,
    color: "#444",
    borderLeft: "2px solid #ddd",
    paddingLeft: 12,
    marginTop: 16,
  },
  code: {
    fontFamily: "'Courier New', monospace",
    fontSize: 11,
    background: "#f5f5f5",
    padding: "6px 10px",
    color: "#555",
    marginTop: 8,
    wordBreak: "break-all",
  },
};

export const dynamic = {
  algoBtn: (on, color) => ({
    padding: "5px 14px",
    fontSize: 12,
    border: `1px solid ${on ? color : "#bbb"}`,
    background: on ? color : "transparent",
    color: on ? "#fff" : "#555",
    cursor: "pointer",
    borderRadius: 0,
  }),
  tabBtn: (on) => ({
    fontSize: 12,
    padding: "4px 0",
    marginRight: 20,
    background: "none",
    border: "none",
    borderBottom: on ? "1px solid #111" : "1px solid transparent",
    color: on ? "#111" : "#888",
    cursor: "pointer",
  }),
  radioRow: (on) => ({
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "6px 10px",
    cursor: "pointer",
    marginBottom: 4,
    borderLeft: on ? "2px solid #111" : "2px solid transparent",
  }),
  barFill: (pct, color) => ({
    width: `${pct}%`,
    height: "100%",
    background: color,
    transition: "width 0.4s",
  }),
  runBtn: (loading) => ({
    padding: "6px 18px",
    fontSize: 12,
    background: "#111",
    color: "#fff",
    border: "none",
    cursor: loading ? "not-allowed" : "pointer",
    borderRadius: 0,
    marginTop: 10,
    opacity: loading ? 0.5 : 1,
  }),
};
